version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgrespass # or use ${POSTGRES_USER}  for example
      POSTGRES_PASSWORD: postgres # or use ${POSTGRES_PASSWORD} for example
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    networks:
      - user-network

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: user-app
    command: /main run -c /config/config.yaml
    volumes:
      - ./config/config.yaml:/config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - user-network

networks:
  user-network:
    driver: bridge